### ISSUE TITLE
Unable to download files from URL that uses Non-ASCII characters

### ISSUE THREAD

**Issue by samperu** [lazaroblanc/Index-of-downloader#2] opened 2021-03-26 22:05 UTC
Good morning 
I try to use your script but it didn´t downloaded any file from the https site, I want to download all files from this https site https://dl.304304.xyz/%E5%B0%9A%E6%9C%AA%E6%95%B4%E7%90%86/%E5%85%B1%E4%BA%AB2020.5.11/content/1_english/
it would help me to improve my english, maybe could you help me.

**Comment by lazaroblanc** [comment] 2021-03-26 23:27
Thank you for your issue @samperu !
I took a look and was able to reproduce your error.
The issue is fixed with the latest commit.
Just download the [latest release ](https://github.com/lazaroblanc/Index-of-downloader/releases/latest) of the script ! :)

**Closed as completed** 2021-03-26 23:27 UTC
Labels: bug

**Comment by rodionemo** [comment] 2025-08-13 14:52
I trying to activate Index of downloader but it's not working can you help me?

**Comment by rodionemo** [comment] 2025-08-13 14:53
I downloaded last update and is still not working

**Comment by lazaroblanc** [comment] 2025-08-14 11:20
> I downloaded last update and is still not working

I haven't updated this repo in 4 years. Can you give me anything to go off as to *why* "it's not working"?
Error message, screenshot, something?
